### ISSUE TITLE
Version numbers for `collectionComponents`

### ISSUE THREAD

**Issue by fschiettecatte** [ga4gh-discovery/ga4gh-case-discovery#21]
Version numbers are for collectionComponents, but not the records items in the `records` components,do we need those to be versioned as well? For example:

```
{
    "meta": {
        "request": {
            "collectionComponents": {
                "records": {
                    "mme": "1.0.0"
                },
            }
        }
    }
}
```

**Comment by Relequestual** [comment]
I'm not sure I full understand what you are asking here.

The version numbers for components are for the format of those components.
Collection components are components that represent information about the group of records, for example a `count` collection component could contain a count of the number of records.

The version of the components used in the records is covered by the root level `meta` object, for example from the proposal:

```
{
  "meta": {
    "response": {
      "collectionComponents": {
        "count": "1.0.0"
      },
      "components": {
        "variant": "1.0.0",
        "phenotype": "1.0.0",
        "contact": "1.0.0",
        "link": "1.0.0"
      }
    },
```

In the example structure you included, what are you trying to convey? I'm not sure what `mme` is in this context.

**Comment by fschiettecatte** [comment]
I am talking about the versions of the actual `record` format in the `collectionComponents`.

**Comment by Relequestual** [comment]
The `records` collection is an array of objects where each object has a `meta` and `components` object.

Do you mean, "the versions of the components in each record"?

If not, I'm afraid you're going to need to be considerably more verbose, as I can't follow you at all on this.

**Comment by fschiettecatte** [comment]
I do mean "the versions of the components in each record"? If the `records` in the response is a collection of objects with `meta` and `components` then version can be embedded into that, but how would I specify version for an "mme" record in the request?

**Comment by Relequestual** [comment]
The records are indeed a collection of objects with meta and components, as you say.
I would think it's unlikely that a server would respond with different versions of the same component, so it makes sense to specify the versions of the components sent in the response at the root level, rather than for every record.

An "MME record" would be a number of components which an MME format would be transformed into. I don't invisage this API having any notion of an "MME record". In fact I'm quite opposed to it, as it would defeat the whole point of using components.

I fairly recently discovered a language agnostic json transformation format, so it's totaly possible for someone from MME to write an "MME to Search API components" transformer, which would work for anyone.

**Comment by Relequestual** [comment]
@fschiettecatte any further comments or questions on this?

**Comment by fschiettecatte** [comment]
Nope.
